name = "liangkw16-readest-web"
main = ".open-next/worker.js"
compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[vars]
PNPM_VERSION = "10.28.1"

[observability]
enabled = false

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
