import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, test } from 'vitest';

const appRoot = process.cwd();
const bridgeRoot = resolve(appRoot, 'src-tauri/plugins/tauri-plugin-native-bridge');

const read = (path: string): string => readFileSync(resolve(appRoot, path), 'utf8');

describe('retired native purchase bridge', () => {
  test('removes the application-level IAP capability flag', () => {
    for (const path of [
      'src/types/system.ts',
      'src/services/appService.ts',
      'src/services/nativeAppService.ts',
    ]) {
      expect(read(path), path).not.toContain('hasIAP');
    }
  });

  test('removes native purchase implementations and their platform dependencies', () => {
    for (const path of [
      'src-tauri/plugins/tauri-plugin-native-bridge/ios/Sources/StoreKitManager.swift',
      'src-tauri/plugins/tauri-plugin-native-bridge/android/src/foss/java/com/readest/native_bridge/BillingManager.kt',
      'src-tauri/plugins/tauri-plugin-native-bridge/android/src/googleplay/java/com/readest/native_bridge/BillingManager.kt',
    ]) {
      expect(existsSync(resolve(appRoot, path)), path).toBe(false);
    }

    const guardedPaths = [
      'src-tauri/plugins/tauri-plugin-native-bridge/src/models.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/src/commands.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/src/desktop.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/src/mobile.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/src/lib.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/build.rs',
      'src-tauri/plugins/tauri-plugin-native-bridge/android/build.gradle.kts',
      'src-tauri/plugins/tauri-plugin-native-bridge/android/src/main/java/NativeBridgePlugin.kt',
      'src-tauri/plugins/tauri-plugin-native-bridge/ios/Package.swift',
      'src-tauri/plugins/tauri-plugin-native-bridge/ios/Sources/NativeBridgePlugin.swift',
      'src-tauri/plugins/tauri-plugin-native-bridge/permissions/default.toml',
      'src-tauri/plugins/tauri-plugin-native-bridge/permissions/autogenerated/reference.md',
      'src-tauri/plugins/tauri-plugin-native-bridge/permissions/schemas/schema.json',
      'src-tauri/gen/android/app/src/main/AndroidManifest.xml',
      'src-tauri/gen/apple/project.yml',
    ];
    const forbidden = [
      'iap_',
      'IAP',
      'StoreKit',
      'BillingManager',
      'com.android.billingclient',
      'com.android.vending.BILLING',
      'In-App Purchase',
    ];

    const violations = guardedPaths.flatMap((path) => {
      const source = read(path);
      return forbidden
        .filter((needle) => source.includes(needle))
        .map((needle) => `${path}: ${needle}`);
    });

    expect(violations).toEqual([]);
    expect(
      existsSync(resolve(bridgeRoot, 'permissions/autogenerated/commands/iap_initialize.toml')),
    ).toBe(false);
  });

  test('keeps the native OAuth commands registered and permitted', () => {
    for (const [path, safariCommand, customTabCommand] of [
      [
        'src-tauri/plugins/tauri-plugin-native-bridge/src/lib.rs',
        'auth_with_safari',
        'auth_with_custom_tab',
      ],
      [
        'src-tauri/plugins/tauri-plugin-native-bridge/build.rs',
        'auth_with_safari',
        'auth_with_custom_tab',
      ],
      [
        'src-tauri/plugins/tauri-plugin-native-bridge/permissions/default.toml',
        'allow-auth-with-safari',
        'allow-auth-with-custom-tab',
      ],
    ] as const) {
      const source = read(path);
      expect(source, path).toContain(safariCommand);
      expect(source, path).toContain(customTabCommand);
    }

    expect(
      read('src-tauri/plugins/tauri-plugin-native-bridge/ios/Sources/NativeBridgePlugin.swift'),
    ).toContain('auth_with_safari');
    expect(
      read(
        'src-tauri/plugins/tauri-plugin-native-bridge/android/src/main/java/NativeBridgePlugin.kt',
      ),
    ).toContain('auth_with_custom_tab');
  });
});
